CREATE DATABASE job_db;
use job_db;
show TABLES;
SELECT * FROM job;
INSERT INTO job (jobDesignation, jobDescription, keyWords, companyName, workExperience, salary) VALUES 
( 'Java Developer', 'Develop and maintain Java-based applications, focusing on back-end components, APIs, and microservices', 'Java, Spring Boot, Microservices', 'Microsoft', 3, 1500000),
( 'Front End Developer', 'Create responsive and user-friendly web interfaces using modern JavaScript frameworks', 'JavaScript, React, HTML, CSS', 'Google', 2, 1300000),
( 'Data Scientist', 'Analyze complex data sets to drive business decisions and improve product features', 'Python, Machine Learning, SQL, Data Analysis', 'Amazon', 4, 1800000),
( 'Backend Developer', 'Design and implement server-side logic and databases for web applications', 'Node.js, Express, MongoDB, RESTful APIs', 'IBM', 3, 1400000),
( 'Full Stack Developer', 'Develop both client and server-side of web applications, ensuring seamless integration', 'JavaScript, React, Node.js, MongoDB', 'Oracle', 5, 2000000),
( 'Machine Learning Engineer', 'Develop and deploy machine learning models to solve complex business problems', 'Python, TensorFlow, Scikit-learn, Deep Learning', 'Intel', 4, 1900000),
( 'DevOps Engineer', 'Implement and manage CI/CD pipelines, automate deployment processes', 'Docker, Kubernetes, Jenkins, AWS', 'Cisco', 3, 1600000),
( 'UI/UX Designer', 'Create intuitive and visually appealing user interfaces for web and mobile applications', 'Figma, Adobe XD, User Research, Prototyping', 'Apple', 2, 1300000),
( 'Cloud Solutions Architect', 'Design and implement scalable cloud infrastructure solutions', 'AWS, Azure, Google Cloud, Terraform', 'Salesforce', 6, 2200000),
( 'Cybersecurity Analyst', 'Protect organization\'s networks and systems from security threats and breaches', 'Network Security, Penetration Testing, Incident Response', 'Dell', 4, 1700000),
( 'Mobile Developer', 'Design and build mobile applications for iOS and Android', 'Swift, Kotlin, React Native, Mobile Apps', 'Spotify', 3, 1500000),
( 'Data Engineer', 'Develop, test, and maintain architectures such as databases and large-scale processing systems', 'Python, Hadoop, SQL, Data Warehousing', 'Netflix', 4, 1700000),
( 'System Administrator', 'Manage and monitor all installed systems and infrastructure', 'Linux, Windows Server, Network Security, Cloud', 'IBM', 5, 1500000),
( 'Software Engineer', 'Develop information systems by designing, developing, and installing software solutions', 'Java, Python, C++, SDLC', 'Adobe', 2, 1450000),
( 'Technical Support Specialist', 'Provide technical support to customers by diagnosing software and hardware problems', 'Technical Support, Troubleshooting, Networking, Hardware', 'HP', 3, 1350000),
( 'IT Project Manager', 'Lead and manage IT projects from inception to completion', 'Project Management, Agile, Scrum, Budgeting', 'Google', 6, 2000000),
( 'Product Manager', 'Oversee the development and delivery of digital products', 'Product Management, UX/UI, Agile, Roadmaps', 'Facebook', 5, 1800000),
( 'Security Engineer', 'Design, implement, and monitor security measures for the protection of computer systems', 'Network Security, Cybersecurity, Penetration Testing', 'Oracle', 4, 1750000),
( 'Web Developer', 'Create and maintain websites and web applications', 'HTML, CSS, JavaScript, PHP, WordPress', 'Walmart', 2, 1250000),
( 'Blockchain Developer', 'Develop and optimize blockchain protocols and smart contracts', 'Blockchain, Solidity, Ethereum, Cryptography', 'Coinbase', 3, 1600000),
( 'AI Researcher', 'Conduct research in artificial intelligence and machine learning to develop innovative solutions', 'AI, Machine Learning, Deep Learning, Python', 'OpenAI', 5, 2200000),
( 'Network Engineer', 'Design and implement computer networks', 'Networking, Cisco, Firewall, Routing, Switching', 'AT&T', 3, 1450000),
( 'Game Developer', 'Develop interactive games for console, PC, and mobile platforms', 'Unity, Unreal Engine, C++, Game Design', 'EA Sports', 4, 1600000),
( 'Business Analyst', 'Analyze business processes to identify inefficiencies and recommend solutions', 'Business Analysis, Requirements Gathering, SQL, Agile', 'Deloitte', 3, 1500000),
( 'Big Data Engineer', 'Develop and manage big data solutions to process and analyze large data sets', 'Hadoop, Spark, SQL, Big Data', 'Yahoo', 4, 1800000),
( 'IoT Developer', 'Develop and implement IoT solutions', 'IoT, Embedded Systems, C, C++, Python', 'Samsung', 2, 1350000),
( 'Cloud Engineer', 'Develop and maintain cloud-based infrastructure', 'AWS, Azure, Google Cloud, Terraform, DevOps', 'Dropbox', 5, 2100000),
( 'IT Consultant', 'Advise clients on how to use information technology to meet their business objectives', 'IT Consulting, Strategy, Cloud, Security', 'Accenture', 6, 1900000),
( 'ERP Consultant', 'Implement and manage ERP systems to improve business processes', 'ERP, SAP, Oracle, Business Analysis', 'Infosys', 5, 1700000),
( 'Penetration Tester', 'Test systems and networks for vulnerabilities by simulating cyberattacks', 'Penetration Testing, Ethical Hacking, Network Security', 'Cisco', 3, 1600000),
( 'Digital Marketing Specialist', 'Develop and implement digital marketing strategies to promote products and services', 'SEO, SEM, Content Marketing, Social Media', 'HubSpot', 2, 1200000),
( 'Automation Engineer', 'Design and implement automation systems for manufacturing and IT processes', 'Automation, PLC, Python, Robotics', 'Tesla', 4, 1800000),
( 'BI Developer', 'Develop business intelligence solutions to support decision-making processes', 'Business Intelligence, SQL, Data Warehousing, Power BI', 'Uber', 3, 1550000),
( 'DevSecOps Engineer', 'Integrate security practices into the DevOps pipeline', 'DevOps, Security, Jenkins, AWS, Docker', 'Red Hat', 4, 1850000),
( 'IT Auditor', 'Assess and evaluate the effectiveness of IT systems and controls', 'IT Auditing, Compliance, Risk Management', 'KPMG', 5, 1700000),
( 'Software QA Engineer', 'Test and ensure the quality of software applications', 'Software Testing, Automation, QA, Selenium', 'Apple', 3, 1450000),
( 'Solutions Architect', 'Design high-level solutions that meet business needs', 'Solutions Architecture, Cloud, Networking, Security', 'Microsoft', 6, 2100000),
( 'Mobile App Tester', 'Test mobile applications for functionality, usability, and performance', 'Mobile Testing, QA, Android, iOS', 'Spotify', 2, 1300000),
( 'Machine Learning Ops Engineer', 'Deploy, monitor, and maintain machine learning models in production', 'MLOps, Python, Docker, Kubernetes', 'Airbnb', 4, 1900000),
( 'Technical Writer', 'Create technical documentation for software, hardware, and IT systems', 'Technical Writing, Documentation, API, SDLC', 'Amazon', 2, 1350000);
